name: Generate and Deploy Weekly Blog Post

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every Monday at 09:00 UTC
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  generate-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate Blog Post
      run: python scripts/generate_blog.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git pull origin main --rebase
        git add content/posts/
        git commit -m "📝 Weekly Blog Post - $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push origin main

    - name: Install Hugo (Extended Version)
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build Hugo Site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
